deploy-as-code/helm/environments/central-instance.yaml

central-instance for mdms and config repos

RAIN-2474 Updated branch name from UAT to

---

deploy-as-code/helm/charts/core-services/egov-pdf/values.yaml

This reverts commit b32cb7f0279394a32ab00c2336b476bcf21f6cf6.

RAIN-2432 : Echallan PDF config removed for UAT deployment

---

deploy-as-code/helm/environments/uat.yaml

RAIN-2346 added is-external-workflow-enabled for

---

deploy-as-code/helm/environments/uat.yaml

EDCR-167 Update content types for DXF filetype

EDCR-167 Update content types for DXF filetype

---

deploy-as-code/helm/environments/epass-uat.yaml

…g and they no longer have an ePass tab.

DIsabled Arogya Setu integration since the Arogya Setu URL not working and they no longer have an ePass tab.

---

deploy-as-code/helm/environments/epass-micro-prod.yaml

…g and they no longer have an ePass tab.

DIsabled Arogya Setu integration since the Arogya Setu URL not working and they no longer have an ePass tab

---

deploy-as-code/helm/charts/core-services/xstate-chatbot/covid-chatbot-values.yaml
deploy-as-code/helm/environments/pb-uat-v2.yaml

Assuming username and password are the same for the new database. If they are different, new secrets will have to be configured.

Deployment configuration for covid chatbot

---

deploy-as-code/helm/environments/pb-prod-v2-secrets.yaml

updated covid-chatbot creds

---

deploy-as-code/helm/environments/uat.yaml

RAIN-2346 Reverted changes made for access

---

deploy-as-code/helm/charts/business-services/dashboard-analytics/values.yaml
deploy-as-code/helm/environments/qa.yaml

Fsm dashboaranalytics memory increase

FSM-441 Fsm dashboaranalytics memory

---

deploy-as-code/helm/environments/mgramseva-dev.yaml

mgram serva dev env, updating the mdms and config repo branches to mgram-dev branches

mgram serva dev env, updating the mdms and config repo branches

---

deploy-as-code/helm/environments/qa.yaml

Added PT Inbox searcher config path to qa.yml

RAIN-2768 Added PT Inbox searcher config path

---

deploy-as-code/helm/environments/qa.yaml

RAIN-2768 Added searcher for Inbox TL

---

deploy-as-code/helm/environments/pb-uat-v2-secrets.yaml

Added auth token value in secret.yaml

added values of chatbot auth token in  pb-uat-v2-secrets.yaml

---

deploy-as-code/helm/environments/qa.yaml

Added new UI payment link for event notification

RAIN-3414 Added new UI payment link

---

deploy-as-code/helm/environments/uat.yaml

RAIN-3414 enabled SMS in UAT

---

deploy-as-code/helm/environments/qa.yaml

RAIN-3414 Added pg service payment reconciliation

---

deploy-as-code/helm/charts/core-services/xstate-webchat/Chart.yaml
deploy-as-code/helm/charts/core-services/xstate-webchat/templates/deployment.yaml
deploy-as-code/helm/charts/core-services/xstate-webchat/templates/ingress.yaml
deploy-as-code/helm/charts/core-services/xstate-webchat/templates/service.yaml
deploy-as-code/helm/charts/core-services/xstate-webchat/values.yaml

Initial commit

---

deploy-as-code/helm/environments/ukd-dev-sdc.yaml

for key mismatch issue in deployment

adding webchat service

---

deploy-as-code/helm/charts/frontend/digit-ui/values.yaml
deploy-as-code/helm/environments/dev.yaml

Reverts egovernments/DIGIT-DevOps#555

Revert "RAIN-4146: Entries for websocket service"

---

deploy-as-code/helm/environments/ukd-prod-sdc.yaml

increase es-data-v1 and es-data-infra-v1

Increase the space of Elasticsearch

---

deploy-as-code/helm/product-release-charts/DIGIT/dependancy_chart-v2.6.yaml

Dependency chart for build of DIGIT 2.6 Release

Dependency chart for build of DIGIT 2.6 Release

---

deploy-as-code/helm/environments/qa.yaml

> Reverts egovernments/DIGIT-DevOps#685

Revert "Multiple replicas of user event"

---

deploy-as-code/helm/environments/qa.yaml

RAIN-4911 Increased replica count to support bulk pdf

---

deploy-as-code/helm/environments/qa.yaml

to test Notification based on channel for real number

RAIN-4911 Enabled SMS for QA

---

deploy-as-code/helm/environments/qa.yaml

Reverts egovernments/DIGIT-DevOps#706
Enabling SMS to test notifications

Revert "RAIN-4911 Disabled SMS to execute bulk scripts"

---

deploy-as-code/helm/environments/qa.yaml

RAIN-4911 Disabled SMS service

---

deploy-as-code/helm/environments/qa.yaml

Reverts egovernments/DIGIT-DevOps#721
Enabling SMS service

Revert "RAIN-4911 Disabled SMS service"

---

deploy-as-code/helm/charts/core-services/national-dashboard-ingest/Chart.yaml
deploy-as-code/helm/charts/core-services/national-dashboard-ingest/templates/deployment.yaml
deploy-as-code/helm/charts/core-services/national-dashboard-ingest/templates/ingress.yaml
deploy-as-code/helm/charts/core-services/national-dashboard-ingest/templates/service.yaml
deploy-as-code/helm/charts/core-services/national-dashboard-ingest/values.yaml
deploy-as-code/helm/charts/core-services/national-dashboard-kafka-pipeline/Chart.yaml
deploy-as-code/helm/charts/core-services/national-dashboard-kafka-pipeline/templates/deployment.yaml
deploy-as-code/helm/charts/core-services/national-dashboard-kafka-pipeline/templates/ingress.yaml
deploy-as-code/helm/charts/core-services/national-dashboard-kafka-pipeline/templates/service.yaml
deploy-as-code/helm/charts/core-services/national-dashboard-kafka-pipeline/values.yaml

Introducing new service charts in central instance branch

RAIN-4633 created dashboard charts for Central Instance

---

deploy-as-code/helm/charts/core-services/national-dashboard-kafka-pipeline/values.yaml

Added default value for module index mapping for kafka pipeline

RAIN:7005 Update values.yaml

---

deploy-as-code/helm/charts/core-services/national-dashboard-kafka-pipeline/values.yaml

Validated the yaml file for env value added

RAIN:7005  Update values.yaml

---

deploy-as-code/helm/environments/dev.yaml
deploy-as-code/helm/environments/qa.yaml

Changes done to create new non-metered applications directly with connectionNos.
These changes would be reverted once the datasets are created for testing.

Bulk Bill Test changes

---

deploy-as-code/helm/environments/dev.yaml

Reverts egovernments/DIGIT-DevOps#862

Revert "Bulk Bill Test changes"

---

deploy-as-code/helm/environments/qa.yaml

RAIN-6821 added ingress to enable SMS

---

deploy-as-code/helm/environments/qa.yaml

Reverts egovernments/DIGIT-DevOps#876

Revert "RAIN -6821 Enabled decryption for qa.yml file"

---

deploy-as-code/helm/environments/central-instance.yaml

Added replica 1 for dashboard analytic to create a pod for it in central instance

RAIN-4633 added replica for dashboard analytic

---

deploy-as-code/helm/environments/qa.yaml

added dag repo location for adaptor integration

RAIN-5190 updated qa.yaml for airflow setup

---

deploy-as-code/helm/environments/qa.yaml

the repo path is changed as it was redirecting to wrong location

RAIN-5190 updated qa.yaml

---

deploy-as-code/helm/environments/qa.yaml

Reverts egovernments/DIGIT-DevOps#864

Revert "RAIN -6821 Reverting Back Bulk Bill Test Changes"

---

deploy-as-code/helm/environments/qa.yaml

Reverts egovernments/DIGIT-DevOps#901

 "RAIN -6821  Back Bulk Bill Test Changes,disabling W&S workflow.

---

deploy-as-code/helm/environments/qa.yaml

Reverts egovernments/DIGIT-DevOps#906

Revert " "RAIN -6821  Back Bulk Bill Test Changes,disabling W&S workflow."

---

deploy-as-code/helm/environments/qa.yaml

Reverts egovernments/DIGIT-DevOps#910

Revert "RAIN - 6821 Disabled workflow for W&S."

---

deploy-as-code/helm/environments/qa.yaml

Reverts egovernments/DIGIT-DevOps#912

Revert "Revert "RAIN - 6821 Disabled workflow for W&S for testing purpose""

---

deploy-as-code/helm/environments/qa.yaml

Reverts egovernments/DIGIT-DevOps#922

 "RAIN-6821 Enabled workflow for ws services "

---

deploy-as-code/helm/environments/qa.yaml

Reverts egovernments/DIGIT-DevOps#928

Revert "RAIN-6821 Disabled workflow for ws services for bulk bill performance…"

---

deploy-as-code/helm/environments/qa.yaml

Reverts egovernments/DIGIT-DevOps#933

Revert "RAIN- 6821 Disabled water workflow for testing."

---

deploy-as-code/helm/charts/cluster-configs/templates/secrets/minio-secret.yaml
deploy-as-code/helm/charts/cluster-configs/values.yaml
deploy-as-code/helm/environments/works-dev-secrets.yaml
deploy-as-code/helm/environments/works-dev.yaml
deploy-as-code/helm/product-release-charts/DIGIT-Works/dependency_chart-works-v1.0.yaml
infra-as-code/terraform/works-dev/main.tf
infra-as-code/terraform/works-dev/outputs.tf

Added support for minio secrets in multiple namespaces

Minio configs

---

deploy-as-code/helm/charts/municipal-services/birth-registration/Chart.yaml
deploy-as-code/helm/charts/municipal-services/birth-registration/templates/deployment.yaml
deploy-as-code/helm/charts/municipal-services/birth-registration/templates/ingress.yaml
deploy-as-code/helm/charts/municipal-services/birth-registration/templates/service.yaml
deploy-as-code/helm/charts/municipal-services/birth-registration/values.yaml

Added a new helm chart for the dev guide sample module - birth registration - under the municipal services directory.

Added new helm chart for birth registration module

---

deploy-as-code/helm/environments/qa.yaml

Reverts egovernments/DIGIT-DevOps#968

Revert "RAIN-6821 Removed privacy changes for user service."

---

deploy-as-code/helm/environments/qa.yaml

Privacy enabled for Property and WS

UM-464 :: Privacy enabled for Property and WS

---

deploy-as-code/helm/environments/qa.yaml

Reverts egovernments/DIGIT-DevOps#1042

Revert "DPG-374: Updating refresh token value"

---

deploy-as-code/helm/charts/core-services/egov-notification-mail/values.yaml

DPG-338-Added filestore address in email service

DPG-338-Filestore changes

---

deploy-as-code/helm/environments/uat.yaml

enabling privacy on uat for user,pt,ws,sw services

Enabling privacy on uat

---

config-as-code/product-release-charts/Sanitation/dependancy_chart-fsm-v1.2.1.yaml

#SM-1376 Vehicle trip issue

---

deploy-as-code/helm/charts/core-services/egov-pg-service/values.yaml

DPG-1021: Added state level tenant id variable

Added State Level Tenant id variable

---

deploy-as-code/helm/environments/ci.yaml

added mgramsewa-dev, mgramsewa-qa, mgramsewa-uat

changes made in deployment jobs

---

deploy-as-code/helm/environments/qa.yaml
deploy-as-code/helm/environments/uat.yaml

Added missing  config for QA & UAT

SM-1384: Build and deployment process

---

deploy-as-code/helm/environments/uat.yaml

Increased request filesize to 70MB

[DPG-959] Increase request size for egov-filestore

---

deploy-as-code/helm/charts/core-services/egov-filestore/values.yaml

Added **spring-servlet-multipart-max-request-size** property in egov-filestore chart values.

Added spring-servlet-multipart-max-request-size property 

---

deploy-as-code/helm/charts/digit-works/backend/muster-roll-service/values.yaml
deploy-as-code/helm/environments/works-dev.yaml

Updated the helm chart for muster roll service

Pfm 2087 helm

---

deploy-as-code/helm/environments/works-qa.yaml

Updated the Persister yaml path for muster roll config

Updated the Persister yaml path for muster roll config

---

deploy-as-code/helm/charts/digit-works/backend/project-management-system/values.yaml

- Add Idgen to project management helm values
- Remove unnecessary indentation

Project Management System YAML refactor, Add Idgen

---

deploy-as-code/helm/environments/works-qa.yaml

Changes in muster roll Indexer path and business service Name

Changes in muster roll

---

deploy-as-code/helm/charts/digit-works/backend/project-management-system/values.yaml

- Changed server path for project management system

Project management system server path change

---

deploy-as-code/helm/environments/works-qa.yaml

Added Project service environment variables

Added Project service environment variables

---

deploy-as-code/helm/charts/digit-works/backend/project-management-system/values.yaml
deploy-as-code/helm/environments/works-dev.yaml

- Change project max limit, offset to default limit, offset
- Add max search limit as 200

Update helm variables for project service

---

deploy-as-code/helm/charts/core-services/audit-service/values.yaml
deploy-as-code/helm/environments/works-dev.yaml

- Add persister file path for project service in helm
- Add enc service host in audit-service values

Add Persister file path for audit-service in helm

---

deploy-as-code/helm/environments/works-qa.yaml

Added project search-max limit

Added project search-max limit

---

deploy-as-code/helm/environments/works-qa.yaml

Added attendance search end point

Added attendance search end point

---

deploy-as-code/helm/environments/works-qa.yaml

PFM-2372 : Boundary Data Updation from punjab to playground

PFM-2372 : Boundary Data Updation from punjab to playground

---

deploy-as-code/helm/environments/ci-secrets.yaml

Changed the cluster from single instance to central instance in both statea and stateb kubeconfigs

changed statea and stateb to central cluster

---

deploy-as-code/helm/environments/works-dev.yaml

- Add persister config file paths for attendance, muster roll and estimate service in audit service environment

Add audit service persister paths

---

deploy-as-code/helm/environments/uat-secrets.yaml

added elasticsearch secrets

---

deploy-as-code/helm/environments/works-qa.yaml

Added the Persister path for audit changes for PFM-2364, 2381 and 2310

Added the Persister path for audit changes for PFM-2364, 2381 and 2310

---

deploy-as-code/helm/environments/works-qa.yaml

Add indexer file path to helm: works-qa.yaml

QA: Added PMS-Indexer

---

deploy-as-code/helm/charts/digit-works/backend/contract-service/Chart.yaml
deploy-as-code/helm/charts/digit-works/backend/contract-service/templates/deployment.yaml
deploy-as-code/helm/charts/digit-works/backend/contract-service/templates/ingress.yaml
deploy-as-code/helm/charts/digit-works/backend/contract-service/templates/service.yaml
deploy-as-code/helm/charts/digit-works/backend/contract-service/values.yaml
deploy-as-code/helm/environments/works-dev.yaml

Please review and take appropriate action

PFM-2121 | contract-service | initial draft of configurations

---

deploy-as-code/helm/charts/digit-works/backend/contract-service/values.yaml

PFM-2121 | contract-service | updated ..

---

deploy-as-code/helm/environments/works-qa.yaml

Updated the estimate business service name

Updated the estimate business service name

---

deploy-as-code/helm/environments/works-qa.yaml

PFM-2579 :: Enabled the Live SMS in QA Env updated the config 

---

deploy-as-code/helm/environments/works-qa.yaml

Refactor.works-QA

---

deploy-as-code/helm/environments/works-qa.yaml

Updated Pfm nm

---

deploy-as-code/helm/charts/core-services/egov-filestore/values.yaml
deploy-as-code/helm/charts/core-services/zuul/values.yaml
deploy-as-code/helm/environments/works-dev.yaml
deploy-as-code/helm/environments/works-qa.yaml

Reverts egovernments/DIGIT-DevOps#1408

Revert "updated works-qa,dev"

---

deploy-as-code/helm/environments/works-qa.yaml

Reverts egovernments/DIGIT-DevOps#1391

Revert "Update works-qa.yaml"

---

deploy-as-code/helm/charts/business-services/egov-hrms/values.yaml
deploy-as-code/helm/charts/core-services/egov-filestore/values.yaml
deploy-as-code/helm/charts/core-services/egov-idgen/values.yaml
deploy-as-code/helm/charts/core-services/egov-localization/values.yaml
deploy-as-code/helm/charts/core-services/egov-location/values.yaml
deploy-as-code/helm/charts/core-services/egov-persister/values.yaml
deploy-as-code/helm/charts/core-services/egov-searcher/values.yaml
deploy-as-code/helm/charts/core-services/egov-user/egov-user-enc-values.yaml
deploy-as-code/helm/charts/core-services/egov-user/egov-user-values.yaml
deploy-as-code/helm/charts/core-services/egov-workflow-v2/values.yaml
deploy-as-code/helm/charts/core-services/egov-workflow/values.yaml
deploy-as-code/helm/charts/core-services/user-otp/values.yaml
deploy-as-code/helm/charts/core-services/zuul/values.yaml
deploy-as-code/helm/environments/works-qa.yaml

Reverts egovernments/DIGIT-DevOps#1365

Revert "Patch2"

---

deploy-as-code/helm/charts/common/values.yaml
deploy-as-code/helm/environments/works-qa.yaml

Reverts egovernments/DIGIT-DevOps#1358

Revert "Changed memory limits for common chart and es-data in works-qa-secrets"

---

deploy-as-code/helm/environments/works-qa.yaml

Reverts egovernments/DIGIT-DevOps#1339

Revert "Added memory limits to sms and mail service"

---

deploy-as-code/helm/environments/works-dev.yaml

Reverts egovernments/DIGIT-DevOps#1364

Revert "Update works-dev.yaml"

---

deploy-as-code/helm/charts/digit-works/backend/expense-calculator/values.yaml

PFM-2147 | musterroll service url configuration

---

deploy-as-code/helm/charts/digit-works/backend/expense-calculator/values.yaml

PFM-2147 | expense bill service url configuration

---

deploy-as-code/helm/environments/central-instance.yaml

Reverts egovernments/DIGIT-DevOps#1476

Revert "Removed cert-manager image name"

---

deploy-as-code/helm/charts/digit-works/backend/expense/values.yaml

PFM-2720 - Update topic names in values.yaml

PFM-2720 : Update topic names in values.yaml

---

deploy-as-code/helm/charts/municipal-services/property-services/values.yaml

Reverts egovernments/DIGIT-DevOps#1503

Revert "Update values.yaml"

---

deploy-as-code/helm/charts/backbone-services/jenkins/values.yaml
deploy-as-code/helm/environments/ci-secrets.yaml
deploy-as-code/helm/environments/ci.yaml

sanitation in unified-env branch
works-uat in digit-works branch

created deployment pipelines for works-uat and sanitation

---

deploy-as-code/helm/charts/digit-works/backend/expense-calculator/values.yaml

PFM-2147 | expense calculator service | contract url configuration

---

deploy-as-code/helm/environments/mukta-uat.yaml

- Change paths from works to mukta
- Change gitsync branch to UAT

Update mukta-uat config file

---

deploy-as-code/helm/charts/digit-works/backend/project/Chart.yaml
deploy-as-code/helm/charts/digit-works/backend/project/templates/deployment.yaml
deploy-as-code/helm/charts/digit-works/backend/project/templates/ingress.yaml
deploy-as-code/helm/charts/digit-works/backend/project/templates/service.yaml
deploy-as-code/helm/charts/digit-works/backend/project/values.yaml
deploy-as-code/helm/environments/works-dev.yaml

- Add Project service chart
- Update environment file to include updated config file paths, updated variable name

Add Project service chart in digit-works

---

deploy-as-code/helm/charts/digit-works/backend/individual/values.yaml
deploy-as-code/helm/environments/works-dev.yaml

PFM-2528: Individual-service helm additions for sms-integration

PFM-2528: Individual-service helm additions for sms-integration

---

deploy-as-code/helm/environments/works-dev.yaml

Modified business service names in Helm env file

---

deploy-as-code/helm/environments/works-uat.yaml

Modified the works-uat.yaml file.

Modified works-uat

---

deploy-as-code/helm/charts/digit-works/backend/expense-calculator/values.yaml

Added MDMS service host in Values.yaml.

Fix calculator helm

---

deploy-as-code/helm/environments/mukta-uat-secrets.yaml
deploy-as-code/helm/environments/mukta-uat.yaml

Reverts egovernments/DIGIT-DevOps#1630

Revert "updated oauth2 configs"

---

deploy-as-code/helm/environments/mukta-uat-secrets.yaml

Reverts egovernments/DIGIT-DevOps#1633

Revert "updated oauth2 secrets"

---

deploy-as-code/helm/environments/mukta-uat-secrets.yaml
deploy-as-code/helm/environments/mukta-uat.yaml

Reverts egovernments/DIGIT-DevOps#1632

Revert "Revert "Revert "updated oauth2 configs"""

---

deploy-as-code/helm/environments/mukta-uat.yaml

PFM-3341 : updated yaml file for mukta

---

deploy-as-code/helm/environments/works-dev.yaml

configure dashboard-analytics to works-config

---

deploy-as-code/helm/environments/works-dev.yaml

dashboard-analytics config schema path

---

deploy-as-code/helm/environments/works-dev.yaml

dashboard-analytics config schema schema path

---

deploy-as-code/helm/charts/core-services/zuul/values.yaml

Reverts egovernments/DIGIT-DevOps#1745

Revert "Revert "Update values.yaml""

---

deploy-as-code/helm/charts/backbone-services/jenkins/values.yaml
deploy-as-code/helm/environments/ci-secrets.yaml
deploy-as-code/helm/environments/ci.yaml

Reverts egovernments/DIGIT-DevOps#1760

Revert "Added deployment pipeline for unified-works-dev"

---

deploy-as-code/helm/charts/municipal-services/property-services/values.yaml

Update values.yaml of Property Services

---

deploy-as-code/helm/charts/digit-works/backend/expense/values.yaml

Add individual host to expense service

---

deploy-as-code/helm/environments/works-qa.yaml

Add dss dev to QA

---

deploy-as-code/helm/charts/backbone-services/jenkins/values.yaml
deploy-as-code/helm/environments/ci-secrets.yaml
deploy-as-code/helm/environments/ci.yaml

Reverts egovernments/DIGIT-DevOps#1870

Revert "added kubeconfig files in ci-secrets"

---

deploy-as-code/helm/environments/unified-dev.yaml

Reverts egovernments/DIGIT-DevOps#1881

Revert "Changed to MSK"

---

deploy-as-code/helm/charts/business-services/dashboard-analytics/values.yaml

Change cache time to 0

---

deploy-as-code/helm/charts/core-services/boundary-service/Chart.yaml
deploy-as-code/helm/charts/core-services/boundary-service/templates/deployment.yaml
deploy-as-code/helm/charts/core-services/boundary-service/templates/ingress.yaml
deploy-as-code/helm/charts/core-services/boundary-service/templates/service.yaml
deploy-as-code/helm/charts/core-services/boundary-service/values.yaml

Added helm charts for boundary-service

Boundary service unified env

---

deploy-as-code/helm/charts/digit-works/utilities/mukta-services/values.yaml

Added Expense Calculator endpoint to get the payable amount for the MR's which are not approved yet .And this is required for the MB validation that we are doing before the Muster Roll update call

Added Expense Calculator config

---

deploy-as-code/helm/charts/accelerators/pgr-ai-chatbot/Chart.yaml
deploy-as-code/helm/charts/accelerators/pgr-ai-chatbot/templates/deployment.yaml
deploy-as-code/helm/charts/accelerators/pgr-ai-chatbot/templates/ingress.yaml
deploy-as-code/helm/charts/accelerators/pgr-ai-chatbot/templates/service.yaml
deploy-as-code/helm/charts/accelerators/pgr-ai-chatbot/values.yaml
deploy-as-code/helm/environments/staging.yaml

Please merge the Helm charts for the pgr-ai-chatbot.

Added deployment charts for PGR AI chatbot

---

deploy-as-code/helm/charts/accelerators/pgr-ai-chatbot/Chart.yaml
deploy-as-code/helm/charts/accelerators/pgr-ai-chatbot/templates/deployment.yaml
deploy-as-code/helm/charts/accelerators/pgr-ai-chatbot/templates/ingress.yaml
deploy-as-code/helm/charts/accelerators/pgr-ai-chatbot/templates/service.yaml
deploy-as-code/helm/charts/accelerators/pgr-ai-chatbot/values.yaml
deploy-as-code/helm/charts/cluster-configs/templates/secrets/pgr-ai-chatbot-secret.yaml
deploy-as-code/helm/environments/staging.yaml

Service needs a secrets template. Added it.

Added a secrets template for the pgr-ai-chatbot

---

deploy-as-code/helm/charts/core-services/gateway/gateway/Chart.yaml
deploy-as-code/helm/charts/core-services/gateway/gateway/templates/deployment.yaml
deploy-as-code/helm/charts/core-services/gateway/gateway/templates/role.yaml
deploy-as-code/helm/charts/core-services/gateway/gateway/templates/rolebinding.yaml
deploy-as-code/helm/charts/core-services/gateway/gateway/templates/service.yaml
deploy-as-code/helm/charts/core-services/gateway/gateway/templates/serviceaccount.yaml
deploy-as-code/helm/charts/core-services/gateway/gateway/values.yaml

Added helm charts for spring cloud gateway .

Spring cloud gateway helm

---

deploy-as-code/helm/charts/frontend/pgr-ui/Chart.yaml

Reverts egovernments/DIGIT-DevOps#2466

Revert "Dpg 2227"

---

deploy-as-code/helm/charts/core-services/gateway/values.yaml

Replaced the image with build which supports rate limiting

Added rate limiting in go script

---

deploy-as-code/helm/charts/core-services/gateway/values.yaml

Added rate limiting to gateway's values.yaml helm chart.

Added rate limiting in helm

---

deploy-as-code/charts/core-services/gateway/values.yaml

Added the latest gateway-kubernetes-discovery image in the init container of gateway helm chart.

Added latest gateway-kubernetes-discovery image

---

deploy-as-code/helm/charts/sunbirdrc-service/sunbirdrc-credential-service/values.yaml

removed // in the url

---

deploy-as-code/helm/charts/sunbirdrc-service/sunbirdrc-credential-service/values.yaml
deploy-as-code/helm/environments/unified-dev.yaml

Sunbird url path

---

deploy-as-code/helm/charts/health-services/referralmanagement/values.yaml

Added to fix the following                                             
2024-05-17 09:36:56.862+0000  INFO --- [080-exec-9] o.e.t.h.RestTemplateLoggingInterceptor   -- TENANTID=null, CORRELATION_ID=78ffc0e1-ec58-4068-b9a8-4cbb6d66d201 : Received response from http://health-project.health:8080/project/v1/_search?limit=1&offset=0&tenantId=mz                                                                                                                                                  
2024-05-17 09:36:56.865+0000 ERROR --- [080-exec-9] o.egov.tracer.ExceptionAdvise            -- TENANTID=null, CORRELATION_ID=78ffc0e1-ec58-4068-b9a8-4cbb6d66d201 : Exception caught in tracer  
org.egov.tracer.model.CustomException: Exception : 404 : [<!doctype html><html lang="en"><head><title>HTTP Status 404 …

added health-project-url

---

deploy-as-code/helm/charts/program-management-services/backend/program-service/Chart.yaml
deploy-as-code/helm/charts/program-management-services/backend/program-service/templates/deployment.yaml
deploy-as-code/helm/charts/program-management-services/backend/program-service/templates/ingress.yaml
deploy-as-code/helm/charts/program-management-services/backend/program-service/templates/service.yaml
deploy-as-code/helm/charts/program-management-services/backend/program-service/values.yaml
deploy-as-code/helm/environments/unified-dev.yaml

Added program-service helm chart and a new namespace

Added program-service helm chart

---

deploy-as-code/helm/charts/program-management-services/backend/program-service/values.yaml

Updated values.yaml

---

deploy-as-code/helm/environments/unified-dev.yaml

Updated unified-dev.yaml in environment directory

Updated unified-dev.yaml

---

deploy-as-code/helm/charts/cluster-configs/values.yaml

Added pms namespace to the db secrets list.

Added pms in db secrets

---

deploy-as-code/helm/charts/urban/pgr-services/values.yaml
deploy-as-code/helm/environments/digit-lts.yaml

- Added mdms-v2 host path
- Updated pgr to point to mdms-v2

Added mdms-service-v2 host path and pointed pgr to it in LTS env

---

deploy-as-code/helm/charts/urban/pgr-services/values.yaml

- Updated MDMS _search endpoint in pgr

updated mdms search endpoint for mdms-v2

---

deploy-as-code/helm/charts/core-services/egov-accesscontrol/values.yaml

mdms host update

---

deploy-as-code/helm/charts/core-services/egov-accesscontrol/values.yaml

- mdms-v2 _search endpoint update

mdms-v2-search-endpointupdate

---

deploy-as-code/helm/charts/sunbirdrc-service/qr-scanner-ui/Chart.yaml
deploy-as-code/helm/charts/sunbirdrc-service/qr-scanner-ui/templates/deployment.yaml
deploy-as-code/helm/charts/sunbirdrc-service/qr-scanner-ui/templates/ingress.yaml
deploy-as-code/helm/charts/sunbirdrc-service/qr-scanner-ui/templates/service.yaml
deploy-as-code/helm/charts/sunbirdrc-service/qr-scanner-ui/templates/subfilter-injection-configmap.yaml
deploy-as-code/helm/charts/sunbirdrc-service/qr-scanner-ui/values.yaml
deploy-as-code/helm/environments/unified-dev.yaml

helm charts for vc ui

---

deploy-as-code/helm/charts/accelerators/egov-birth-service/Chart.yaml
deploy-as-code/helm/charts/accelerators/egov-birth-service/templates/deployment.yaml
deploy-as-code/helm/charts/accelerators/egov-birth-service/templates/ingress.yaml
deploy-as-code/helm/charts/accelerators/egov-birth-service/templates/service.yaml
deploy-as-code/helm/charts/accelerators/egov-birth-service/values.yaml

- Added helm chart for egov-birth-service

Added helm chart for egov-birth-service

---

deploy-as-code/helm/charts/sunbirdrc-service/sunbirdrc-credential-service/values.yaml

helm charts updated for rc adapter service

helm chart updated for rc

---

deploy-as-code/helm/charts/sunbirdrc-service/sunbirdrc-credential-service/values.yaml

helm updates

---

deploy-as-code/helm/charts/sunbirdrc-service/sunbirdrc-credential-service/values.yaml

Sunbird helm chart update

---

deploy-as-code/helm/charts/sunbirdrc-service/sunbirdrc-credential-service/values.yaml

removed redis

---

deploy-as-code/helm/environments/unified-mukta-qa.yaml

Added zuul and whitelist configuration

UCEM-746 : Update unified-mukta-qa.yaml

---

deploy-as-code/helm/charts/mukta/mukta-user-otp/values.yaml

Added sms isrequired and other params

UCEM-746 : Update values.yaml

---

deploy-as-code/helm/charts/digit-works/backend/measurement-registry/values.yaml

* mdms host change
* reverting host name change

Added lts changes for unified-dev env

---

deploy-as-code/helm/environments/unified-works-qa.yaml

WIll revert back this change once the migration is done

Updated the mdms host for CBO migration

---

deploy-as-code/helm/charts/health-services/transformer/values.yaml

added topics for the following services:
1. stock ( stock reconciliation topic)
2. referral (referral, hf referral, hf service task referral, side effect)

added topics for referral flow in transformer values

---

deploy-as-code/helm/charts/digit-works/utilities/works-pdf/values.yaml

UCEM-765: Update values.yaml

---

deploy-as-code/helm/charts/health-services/plan-service/values.yaml
deploy-as-code/helm/environments/unified-health-dev.yaml

https://digit-discuss.atlassian.net/jira/software/c/projects/HCMPRE/boards/298?selectedIssue=HCMPRE-862

Adding census host in unified-health-dev environment

---

deploy-as-code/helm/charts/health-services/plan-service/values.yaml

changes in chart

---

deploy-as-code/helm/charts/health-services/resource-generator/Chart.yaml
deploy-as-code/helm/charts/health-services/resource-generator/templates/deployment.yaml
deploy-as-code/helm/charts/health-services/resource-generator/templates/ingress.yaml
deploy-as-code/helm/charts/health-services/resource-generator/templates/service.yaml
deploy-as-code/helm/charts/health-services/resource-generator/values.yaml

resource generator added

---

deploy-as-code/helm/charts/health-services/census-service/values.yaml
deploy-as-code/helm/charts/health-services/plan-service/values.yaml

values added to census and plan chart

values added to census and plan chart

---

deploy-as-code/helm/charts/health-services/census-service/values.yaml

indentation mismatch were fixed.

Updated values

---

deploy-as-code/helm/environments/digit-sandbox.yaml

otp validation true, sandboxpui config added, workbench-ui added

otp validation true, sandboxpui config added, workbench-ui added

---

deploy-as-code/helm/charts/health-services/health-hrms/values.yaml
deploy-as-code/helm/environments/unified-health-uat.yaml

Adding microplan implementation partner and website link for email

---

deploy-as-code/helm/environments/unified-urban-dev.yaml

Reverts egovernments/DIGIT-DevOps#3341

Revert "Update global config file path and tenantid"

---

deploy-as-code/helm/charts/core-services/digit-rag/Chart.yaml
deploy-as-code/helm/charts/core-services/digit-rag/templates/deployment.yaml
deploy-as-code/helm/charts/core-services/digit-rag/templates/ingress.yaml
deploy-as-code/helm/charts/core-services/digit-rag/templates/service.yaml
deploy-as-code/helm/charts/core-services/digit-rag/values.yaml

Added helm chart for DIGIT-RAG

Added helm chart for digit-rag

---

deploy-as-code/helm/charts/health-services/health-attendance/values.yaml

New Env Variable -
- Added env variable and disabled attendance register creation while staff creation

Updated env for health attendance service

---

deploy-as-code/helm/charts/health-services/health-attendance/values.yaml
deploy-as-code/helm/charts/health-services/health-expense-calculator/Chart.yaml
deploy-as-code/helm/charts/health-services/health-expense-calculator/templates/deployment.yaml
deploy-as-code/helm/charts/health-services/health-expense-calculator/templates/ingress.yaml
deploy-as-code/helm/charts/health-services/health-expense-calculator/templates/service.yaml
deploy-as-code/helm/charts/health-services/health-expense-calculator/values.yaml
deploy-as-code/helm/charts/health-services/health-expense/Chart.yaml
deploy-as-code/helm/charts/health-services/health-expense/templates/deployment.yaml
deploy-as-code/helm/charts/health-services/health-expense/templates/ingress.yaml
deploy-as-code/helm/charts/health-services/health-expense/templates/service.yaml
deploy-as-code/helm/charts/health-services/health-expense/values.yaml
deploy-as-code/helm/charts/health-services/health-muster-roll/Chart.yaml
deploy-as-code/helm/charts/health-services/health-muster-roll/templates/deployment.yaml
deploy-as-code/helm/charts/health-services/health-muster-roll/templates/ingress.yaml
deploy-as-code/helm/charts/health-services/health-muster-roll/templates/service.yaml
deploy-as-code/helm/charts/health-services/health-muster-roll/values.yaml
deploy-as-code/helm/environments/unified-health-uat.yaml

All the devops changes related to payments are here.

All the devops changes

---

deploy-as-code/helm/charts/frontend/payments-ui/Charts.yml
deploy-as-code/helm/charts/frontend/payments-ui/templates/deployment.yaml
deploy-as-code/helm/charts/frontend/payments-ui/templates/ingress.yaml
deploy-as-code/helm/charts/frontend/payments-ui/templates/service.yaml
deploy-as-code/helm/charts/frontend/payments-ui/templates/subfilter-injection-configmap.yaml
deploy-as-code/helm/charts/frontend/payments-ui/values.yml
deploy-as-code/helm/charts/health-services/health-expense/values.yaml
deploy-as-code/helm/environments/unified-health-uat.yaml

All the UI devops changes are added here.

UI devops changes

---

deploy-as-code/helm/charts/accelerators/enc-vault-service/Chart.yaml
deploy-as-code/helm/charts/accelerators/enc-vault-service/templates/deployment.yaml
deploy-as-code/helm/charts/accelerators/enc-vault-service/templates/ingress.yml
deploy-as-code/helm/charts/accelerators/enc-vault-service/templates/service.yaml
deploy-as-code/helm/charts/accelerators/enc-vault-service/values.yaml

vault enc svc helm charts

---

deploy-as-code/helm/charts/accelerators/enc-vault-service/values.yaml

service name udpated in the helm charts

vault helm charts updated

---

deploy-as-code/helm/charts/accelerators/vault-enc-service/Chart.yaml
deploy-as-code/helm/charts/accelerators/vault-enc-service/templates/deployment.yaml
deploy-as-code/helm/charts/accelerators/vault-enc-service/templates/ingress.yml
deploy-as-code/helm/charts/accelerators/vault-enc-service/templates/service.yaml
deploy-as-code/helm/charts/accelerators/vault-enc-service/values.yaml

names updated

---

deploy-as-code/helm/charts/accelerators/vault-enc-service/values.yaml
deploy-as-code/helm/environments/digit-lts.yaml

updated env values for vault

---

deploy-as-code/helm/charts/accelerators/vault-enc-service/values.yaml

port changed to string

---

deploy-as-code/helm/charts/accelerators/vault-enc-service/values.yaml

Vault port

---

deploy-as-code/helm/environments/digit-lts.yaml

host updated

---

deploy-as-code/helm/environments/digit-lts.yaml

Vault host updated

---

deploy-as-code/helm/environments/digit-lts.yaml

http ujpdated in vault host

---

deploy-as-code/helm/environments/digit-lts.yaml

host name updated

---

deploy-as-code/helm/charts/accelerators/vault-enc-service/values.yaml

encrypt path udpated

---

deploy-as-code/helm/charts/accelerators/vault-enc-service/values.yaml

encrypt host updated

---

deploy-as-code/helm/charts/accelerators/vault-enc-service/values.yaml

vault url name changed

---

deploy-as-code/helm/charts/common-services/individual/values.yaml

vault enc client helm chart

---

deploy-as-code/helm/environments/digit-lts.yaml

name changed to vault-new

---

deploy-as-code/helm/charts/accelerators/account-service/Chart.yaml
deploy-as-code/helm/charts/accelerators/account-service/templates/deployment.yaml
deploy-as-code/helm/charts/accelerators/account-service/templates/ingress.yaml
deploy-as-code/helm/charts/accelerators/account-service/templates/service.yaml
deploy-as-code/helm/charts/accelerators/account-service/values.yaml

account svc heml charts open telemetry

account svc heml charts open telemetry

---

deploy-as-code/helm/charts/accelerators/account-service/values.yaml

updated repo name

---

deploy-as-code/helm/charts/accelerators/account-service/Chart.yaml

helm chart updated

---

deploy-as-code/helm/charts/accelerators/account-service/values.yaml

container registry updated

---

deploy-as-code/helm/charts/accelerators/account-service/values.yaml

port updated

---

deploy-as-code/helm/charts/accelerators/account-service/values.yaml

jaeger endpoint updated

---

deploy-as-code/helm/charts/frontend/citizen/values.yaml
deploy-as-code/helm/charts/frontend/dss-dashboard/values.yaml
deploy-as-code/helm/charts/frontend/employee/values.yaml
deploy-as-code/helm/charts/urban/digit-ui/values.yaml
deploy-as-code/helm/charts/utilities/boundary-bulk-bff/values.yaml
deploy-as-code/helm/environments/unified-qa.yaml
deploy-as-code/helm/environments/unified-urban-qa.yaml

Update resource limit for citizen,employee,digit-ui,dss,boundary-bulk-bff services

---

deploy-as-code/helm/charts/health-services/project-factory/values.yaml

Making memory as string in Project factory

---

deploy-as-code/helm/charts/health-services/project-factory/values.yaml

Project factory 

---

deploy-as-code/helm/charts/health-services/census-service/values.yaml
deploy-as-code/helm/charts/health-services/facility/values.yaml
deploy-as-code/helm/charts/health-services/health-hrms/values.yaml
deploy-as-code/helm/charts/health-services/household/values.yaml
deploy-as-code/helm/charts/health-services/product/values.yaml

Cpu alloted to hrms, product, census and household

Cpu alloted to hrms, product, census and household

---

deploy-as-code/helm/charts/health-services/geopode-adapter/values.yaml

Changing spelling

---

deploy-as-code/helm/charts/health-services/geopode-adapter/values.yaml

mdms api change

---

deploy-as-code/helm/charts/urban/pgr-camunda-services/Chart.yaml
deploy-as-code/helm/charts/urban/pgr-camunda-services/templates/deployment.yaml
deploy-as-code/helm/charts/urban/pgr-camunda-services/templates/ingress.yaml
deploy-as-code/helm/charts/urban/pgr-camunda-services/templates/service.yaml
deploy-as-code/helm/charts/urban/pgr-camunda-services/values.yaml

camunda pgr helm charts

---

deploy-as-code/helm/charts/accelerators/pgr-camunda-services/Chart.yaml
deploy-as-code/helm/charts/accelerators/pgr-camunda-services/templates/deployment.yaml
deploy-as-code/helm/charts/accelerators/pgr-camunda-services/templates/ingress.yaml
deploy-as-code/helm/charts/accelerators/pgr-camunda-services/templates/service.yaml
deploy-as-code/helm/charts/accelerators/pgr-camunda-services/values.yaml

pgr camunda services

---

deploy-as-code/helm/charts/accelerators/pgr-camunda-services/values.yaml

namespace udpated

---

deploy-as-code/helm/charts/accelerators/pgr-camunda-services/values.yaml

db url updated

---

deploy-as-code/helm/charts/core-services/egov-accesscontrol/values.yaml
deploy-as-code/helm/charts/core-services/egov-enc-service/values.yaml
deploy-as-code/helm/charts/core-services/egov-filestore/values.yaml
deploy-as-code/helm/charts/core-services/egov-localization/values.yaml
deploy-as-code/helm/charts/core-services/egov-location/values.yaml
deploy-as-code/helm/charts/core-services/egov-mdms-service/values.yaml
deploy-as-code/helm/charts/core-services/egov-otp/values.yaml
deploy-as-code/helm/charts/core-services/egov-url-shortening/values.yaml
deploy-as-code/helm/charts/core-services/egov-user/egov-user-values.yaml
deploy-as-code/helm/charts/core-services/egov-workflow-v2/values.yaml
deploy-as-code/helm/charts/core-services/mdms-v2/values.yaml
deploy-as-code/helm/charts/core-services/service-request/values.yaml
deploy-as-code/helm/charts/core-services/user-otp/values.yaml

Added fixed CPU and memory resource limits to services

Added fixed CPU and memory resource limits to services

---

deploy-as-code/helm/charts/core-services/localisationgo/Chart.yaml
deploy-as-code/helm/charts/core-services/localisationgo/templates/deployment.yaml
deploy-as-code/helm/charts/core-services/localisationgo/templates/service.yaml
deploy-as-code/helm/charts/core-services/localisationgo/values.yaml

go localisation code

---

deploy-as-code/helm/charts/core-services/localisationgo/Chart.yaml

chart.yaml file updated

---

deploy-as-code/helm/charts/common-services/individual/values.yaml
deploy-as-code/helm/charts/core-services/egov-user/egov-user-enc-values.yaml
deploy-as-code/helm/charts/health-services/health-expense-calculator/values.yaml
deploy-as-code/helm/charts/health-services/health-individual/values.yaml
deploy-as-code/helm/environments/unified-dev.yaml
deploy-as-code/helm/environments/unified-health-dev.yaml
deploy-as-code/helm/environments/unified-health-qa.yaml
deploy-as-code/helm/environments/unified-health-uat.yaml
deploy-as-code/helm/environments/unified-qa.yaml
deploy-as-code/helm/environments/unified-uat.yaml

Verified state level tenant id in unified qa and unified uat egov-enc-service and egov-user services `pg`. which is kept as is.
In unified dev environment, it was inconsistent which is now changed to dev only.

Resolved inconsistent State level tenant id issue

---

deploy-as-code/helm/environments/unified-health-qa.yaml

Reverts egovernments/DIGIT-DevOps#3889

Revert "Update Hierarchy Name for unified-health-qa ENV"

---

deploy-as-code/helm/charts/core-services/workflowgo/Chart.yaml
deploy-as-code/helm/charts/core-services/workflowgo/templates/deployment.yaml
deploy-as-code/helm/charts/core-services/workflowgo/templates/ingress.yaml
deploy-as-code/helm/charts/core-services/workflowgo/templates/service.yaml
deploy-as-code/helm/charts/core-services/workflowgo/values.yaml

workflow digit3

---

deploy-as-code/helm/charts/frontend/dashboard-ui/Chart.yaml
deploy-as-code/helm/charts/frontend/dashboard-ui/templates/deployment.yaml
deploy-as-code/helm/charts/frontend/dashboard-ui/templates/ingress.yaml
deploy-as-code/helm/charts/frontend/dashboard-ui/templates/service.yaml
deploy-as-code/helm/charts/frontend/dashboard-ui/templates/subfilter-injection-configmap.yaml
deploy-as-code/helm/charts/frontend/dashboard-ui/values.yaml
deploy-as-code/helm/environments/unified-health-dev.yaml
deploy-as-code/helm/environments/unified-health-qa.yaml
deploy-as-code/helm/environments/unified-health-uat.yaml

Dashboard UI for jenkins

---

deploy-as-code/helm/environments/unified-health-uat.yaml

GlobalConfig for Dashboard UI in uat

GlobalConfig for Dashboard UI in uat

---

deploy-as-code/helm/environments/unified-health-dev.yaml
deploy-as-code/helm/environments/unified-health-qa.yaml
deploy-as-code/helm/environments/unified-health-uat.yaml

Dashboard UI global configs for dev, qa

Dashboard UI global configs for dev, qa

---

deploy-as-code/helm/environments/unified-health-qa.yaml

Reverts egovernments/DIGIT-DevOps#3992

Revert "Revert "Update unified-health-qa.yaml""

---

deploy-as-code/helm/environments/unified-uat.yaml

digit studio config map injection updated the position

updated the positioning

---

deploy-as-code/helm/environments/unified-dev.yaml

Inbocxmemory change
